### ISSUE TITLE
Aqua misses some ambiguities

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaTesting/Aqua.jl#91] opened 2022-12-17 00:33 UTC
I didn't see an existing issue for this. We recently found, over at Clima, that Aqua sometimes misses method ambiguities:

### Aqua catches ambiguity
```julia
module BarMod
abstract type ABar end
struct Bar <: ABar end
bar(::Bar, ::ABar) = 1
bar(::ABar, ::Bar) = 2
end
import .BarMod
# BarMod.bar(BarMod.Bar(), BarMod.Bar()) # confirm ambiguity
using Aqua
Aqua.detect_ambiguities(BarMod)
```

### Aqua misses ambiguity
```julia
module FooMod
struct Foo{A,B} end
foo(::Foo{A,<:Any}, ::A) where {A} = 1
foo(::Foo{<:Any,A}, ::A) where {A} = 2
end
import .FooMod
# FooMod.foo(FooMod.Foo{Int,Int}(), 1) # confirm ambiguity
using Aqua
Aqua.detect_ambiguities(FooMod)
```

**Comment by vtjnash** [comment] 2022-12-20 17:21
The problem is that typeintersect cannot compute the best answer here, so we conservatively answer false for `Base.isambiguous`
```
julia> a.sig
Tuple{typeof(Main.FooMod.foo), Main.FooMod.Foo{A}, A} where A

julia> b.sig
Tuple{typeof(Main.FooMod.foo), Main.FooMod.Foo{<:Any, A}, A} where A

julia> typeintersect(b.sig, a.sig)
Tuple{typeof(Main.FooMod.foo), Main.FooMod.Foo{A1, A}, A} where {A, A1}
# optimal would be Tuple{typeof(Main.FooMod.foo), Main.FooMod.Foo{A, A}, A} where A
```

**Comment by fingolfin** [comment] 2023-06-01 14:12
This seems to be a Julia issue, and logged there, so closing it here. Thank you all for reporting, analyzing, and re-reporting to Julia!

**Closed by fingolfin** 2023-06-01 14:12 UTC
