### ISSUE TITLE
Add ExplicitImports

### ISSUE THREAD

**Issue by gdalle** [JuliaTesting/Aqua.jl#273] opened 2024-03-20 05:52 UTC
New package useful to check that there is no implicit import

https://ericphanson.github.io/ExplicitImports.jl/stable/

**Comment by lgoettgens** [comment] 2024-03-20 09:11
Duplicate of https://github.com/JuliaTesting/Aqua.jl/issues/268

**Closed by lgoettgens** 2024-03-20 09:11 UTC

**Comment by gdalle** [comment] 2024-03-20 10:14
sorry
