### ISSUE TITLE
How can I exclude `kwarg` methods from `test_ambiguities`

### ISSUE THREAD

**Issue by fingolfin** [JuliaTesting/Aqua.jl#227] opened 2023-10-31 08:04 UTC
I just did
```
using Aqua, Nemo
Aqua.test_ambiguities(Nemo; exclude=[rand, divexact, ==, *, +, -, evaluate])
```
but this still reported e.g. this:
```
Ambiguity #1
kwcall(::Any, ::typeof(AbstractAlgebra.divexact), a::T, b::AbstractAlgebra.FracElem{T}) where T<:RingElem @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/dsta0/src/Fraction.jl:605
kwcall(::Any, ::typeof(AbstractAlgebra.divexact), a::Nemo.ZZRingElem, b::AbstractAlgebra.FracElem) @ Nemo ~/Projekte/OSCAR/Nemo.jl/src/flint/adhoc.jl:496

Possible fix, define
  kwcall(::Any, ::typeof(AbstractAlgebra.divexact), ::T, ::AbstractAlgebra.FracElem{T}) where T<:Nemo.ZZRingElem
```
I already asked it to exclude `divexact`, but that doesn't work here because it is a `kwcall`.

How can I get it to exclude this kind of method?

Actually to me ideally excluding `divexact` already would have excluded those, but I can live with having to specify yet another exclusion, I just don't know how to do it for those above

**Comment by lgoettgens** [comment] 2023-10-31 08:25
Duplicate of https://github.com/JuliaTesting/Aqua.jl/issues/79

There is already https://github.com/JuliaTesting/Aqua.jl/pull/204 fixing exactly this, that is merely waiting for review.

**Closed** 2023-10-31 08:25 UTC

**Comment by fingolfin** [comment] 2023-10-31 08:58
Sorry -- I *did* search for existing issues, but stupidly only for "kwarg" :-(
