### ISSUE TITLE
Ambiguity check errors on Julia 1.0: `type UnionAll has no field name`

### ISSUE THREAD

**Issue by devmotion** [JuliaTesting/Aqua.jl#141] opened 2023-06-18 14:59 UTC
In https://github.com/JuliaStats/StatsBase.jl/pull/866, I observed test errors of the ambiguity check on Julia 1.0 which seem to be caused by a bug in Aqua (see, e.g., https://github.com/JuliaStats/StatsBase.jl/actions/runs/5298486934/jobs/9590870427?pr=866):
```julia
┌ Error: Failed to obtain a function from `Method`.
│   exception =
│    type UnionAll has no field name
│    Stacktrace:
│     [1] getproperty at ./sysimg.jl:15 [inlined]
│     [2] getobj(::Method) at /home/runner/.julia/packages/Aqua/BhBic/src/ambiguities.jl:168
...
```

**Comment by fingolfin** [comment] 2023-06-18 15:45
Thank you for the report. I think this is a duplicate of issue #49.

**Closed** 2023-06-19 22:38 UTC
